[package]
name = "writer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "candle_writer"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlx = { workspace = true }
rdkafka = { workspace = true }
futures = { workspace = true }
tokio-stream = { workspace = true }
bytes = { workspace = true }

common = { path = "../common" }
connections = { path = "../connections" }
dotenvy = { workspace = true }