//! Core data types for the trading bot

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};
use uuid::Uuid;

/// A candlestick (OHLCV) data structure
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Candle {
    /// Timestamp of the candle
    pub time: DateTime<Utc>,
    /// Symbol identifier
    pub symbol: String,
    /// Timeframe (1m, 5m, 15m, 1h, 4h, 1d)
    pub timeframe: crate::timeframe::Timeframe,
    /// Opening price
    pub open: f64,
    /// Highest price
    pub high: f64,
    /// Lowest price
    pub low: f64,
    /// Closing price
    pub close: f64,
    /// Trading volume
    pub volume: f64,
    /// Whether this is the final candle for this period
    pub is_final: bool,
}

// Timeframe enum is defined in timeframe.rs

// Timeframe From implementations are handled in timeframe.rs

/// Indicator state for incremental calculations
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IndicatorState {
    /// EMA values
    pub ema: Option<EmaState>,
    /// RSI values
    pub rsi: Option<RsiState>,
    /// MACD values
    pub macd: Option<MacdState>,
    /// ATR values
    pub atr: Option<AtrState>,
    /// ADX values
    pub adx: Option<AdxState>,
    /// Bollinger Bands values
    pub bb: Option<BbState>,
    /// Stochastic values
    pub stoch: Option<StochState>,
    /// VWAP values
    pub vwap: Option<VwapState>,
    /// OBV values
    pub obv: Option<ObvState>,
}

/// EMA state for incremental calculation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmaState {
    pub ema20: f64,
    pub ema50: f64,
    pub ema200: f64,
    pub alpha20: f64,
    pub alpha50: f64,
    pub alpha200: f64,
}

/// RSI state for incremental calculation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RsiState {
    pub avg_gain: f64,
    pub avg_loss: f64,
}

/// MACD state for incremental calculation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MacdState {
    pub fast_ema: f64,
    pub slow_ema: f64,
    pub signal_ema: f64,
}

/// ATR state for incremental calculation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AtrState {
    pub tr: f64,
    pub atr: f64,
}

/// ADX state for incremental calculation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdxState {
    pub dm_plus: f64,
    pub dm_minus: f64,
    pub tr: f64,
    pub adx: f64,
}

/// Bollinger Bands state for incremental calculation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BbState {
    pub mean: f64,
    pub variance: f64,
}

/// Stochastic state for incremental calculation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StochState {
    pub k: f64,
    pub d: f64,
}

/// VWAP state for incremental calculation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VwapState {
    pub cum_pv: f64,
    pub cum_volume: f64,
}

/// OBV state for incremental calculation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ObvState {
    pub obv: f64,
}

/// Raw signal generated by indicator calculations
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RawSignal {
    /// Timestamp of the signal
    pub time: DateTime<Utc>,
    /// Symbol identifier
    pub symbol: String,
    /// Timeframe
    pub timeframe: crate::timeframe::Timeframe,
    /// Signal score (0.0 to 1.0)
    pub score: f64,
    /// Raw indicator scores
    pub indicator_scores: Vec<f64>,
    /// Signal type
    pub signal_type: SignalType,
}

/// Signal type enumeration
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq)]
pub enum SignalType {
    /// Long signal
    Long,
    /// Short signal
    Short,
    /// Neutral signal
    Neutral,
}

/// Final signal with ML scoring
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signal {
    /// Timestamp of the signal
    pub time: DateTime<Utc>,
    /// Symbol identifier
    pub symbol: String,
    /// Timeframe
    pub timeframe: crate::timeframe::Timeframe,
    /// Final score (0.0 to 1.0)
    pub final_score: f64,
    /// ML score
    pub ml_score: f64,
    /// Heuristic score
    pub heur_score: f64,
    /// Reason for the signal
    pub reason: String,
    /// Model version
    pub model_version: String,
    /// Signal identifier for idempotency
    pub signal_id: Uuid,
}

/// Trade intent generated by the scoring system
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TradeIntent {
    /// Timestamp of the intent
    pub time: DateTime<Utc>,
    /// Symbol identifier
    pub symbol: String,
    /// Timeframe
    pub timeframe: crate::timeframe::Timeframe,
    /// Trade direction
    pub side: TradeSide,
    /// Quantity to trade
    pub quantity: f64,
    /// Stop loss price
    pub stop_loss: Option<f64>,
    /// Take profit prices
    pub take_profit: Option<Vec<f64>>,
    /// Final score
    pub score: f64,
    /// Features hash
    pub features_hash: Uuid,
    /// Signal identifier
    pub signal_id: Uuid,
}

/// Trade side enumeration
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq)]
pub enum TradeSide {
    /// Buy/Long
    Buy,
    /// Sell/Short
    Sell,
}

/// Order event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderEvent {
    /// Timestamp of the event
    pub time: DateTime<Utc>,
    /// Symbol identifier
    pub symbol: String,
    /// Order ID
    pub order_id: String,
    /// Order type
    pub order_type: OrderType,
    /// Order side
    pub side: TradeSide,
    /// Quantity
    pub quantity: f64,
    /// Price
    pub price: Option<f64>,
    /// Status
    pub status: OrderStatus,
    /// Event type
    pub event_type: OrderEventType,
}

/// Order type enumeration
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq)]
pub enum OrderType {
    /// Market order
    Market,
    /// Limit order
    Limit,
    /// Stop market order
    StopMarket,
    /// Take profit market order
    TakeProfitMarket,
}

/// Order status enumeration
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq)]
pub enum OrderStatus {
    /// New order
    New,
    /// Filled
    Filled,
    /// Partially filled
    PartiallyFilled,
    /// Canceled
    Canceled,
    /// Rejected
    Rejected,
}

/// Order event type enumeration
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq)]
pub enum OrderEventType {
    /// Order placed
    Placed,
    /// Order filled
    Filled,
    /// Order canceled
    Canceled,
    /// Order failed
    Failed,
}

/// Position update event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PositionUpdate {
    /// Timestamp of the update
    pub time: DateTime<Utc>,
    /// Symbol identifier
    pub symbol: String,
    /// Position side
    pub side: TradeSide,
    /// Position size
    pub size: f64,
    /// Average entry price
    pub entry_price: f64,
    /// Unrealized profit/loss
    pub unrealized_pnl: f64,
    /// Leverage
    pub leverage: u16,
    /// Liquidation price
    pub liquidation_price: Option<f64>,
}

/// Exit decision event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExitDecision {
    /// Timestamp of the decision
    pub time: DateTime<Utc>,
    /// Symbol identifier
    pub symbol: String,
    /// Reason for exit
    pub reason: String,
    /// Action to take
    pub action: ExitAction,
    /// Signal identifier
    pub signal_id: Uuid,
}

/// Exit action enumeration
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq)]
pub enum ExitAction {
    /// Close position immediately
    Close,
    /// Tighten stop loss
    TightenSl,
    /// Trail stop loss
    TrailSl,
    /// Scale out
    ScaleOut,
    /// Extend take profit
    ExtendTp,
}