[package]
name = "connections"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "connections"
path = "src/main.rs"

[lib]
name = "connections_lib"
path = "src/lib.rs"

[dependencies]
rustls = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }

dotenvy = { workspace = true }

reqwest = { workspace = true }
url = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
chrono = { workspace = true }

axum = { workspace = true }
tower-http = { workspace = true }

sqlx = { workspace = true }
uuid = { workspace = true }

rdkafka = { workspace = true }

tokio-tungstenite = { workspace = true }
tokio-stream = { workspace = true }
