[package]
name = "db_init"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "db_init"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }

tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tokio-postgres = { workspace = true, features = ["with-uuid-1", "with-serde_json-1"] }

anyhow = { workspace = true }
thiserror = { workspace = true }

# Для поиска файлов и сортировки
walkdir = "2"
