[package]
name = "ingestor"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ingestor_pairs"
path = "src/main.rs"

[[bin]]
name = "load_candles"
path = "src/bin/load_candles.rs"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
sqlx = { workspace = true }
futures = { workspace = true }
tokio-stream = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

common = { path = "../common" }
connections = { path = "../connections" }
dotenvy = { workspace = true }

