[package]
name = "telemetry"
version = "0.1.0"
edition = "2021"

[lib]
name = "telemetry"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1.0", features = ["derive"] }
metrics = "0.23"

# Local dependencies
binance_rest = { path = "../binance_rest" }
binance_ws = { path = "../binance_ws" }
db_init = { path = "../db" }
kafka_client = { path = "../kafka" }
