[package]
name = "data_access"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }
dashmap = "6.0"
serde = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
common = { path = "../common" }