-- 090_super_entry_signals.sql
-- DDL for Super Entry Strategy signals table
-- Generated signals from the ML-based Super Entry model

CREATE TABLE IF NOT EXISTS trade.super_entry_signals (
    time            TIMESTAMPTZ NOT NULL,
    time_ms         BIGINT NOT NULL,
    symbol          TEXT NOT NULL,
    symbol_id       BIGINT NOT NULL,
    tf_minutes      SMALLINT NOT NULL,
    side            SMALLINT NOT NULL,           -- 1=LONG, -1=SHORT
    entry_price     FLOAT8 NOT NULL,
    sl_price        FLOAT8 NOT NULL,
    tp_price        FLOAT8 NOT NULL,
    p_super         REAL NOT NULL,               -- P(super move) from model
    p_long          REAL NOT NULL,               -- P(direction=LONG) from model
    combined_score  REAL NOT NULL,               -- combined scorer output
    dir_confidence  REAL NOT NULL DEFAULT 0.0,   -- directional confidence |p_long - 0.5|
    strategy        TEXT NOT NULL DEFAULT 'super_entry_v1',
    reason          JSONB,                       -- full metadata (target_pct, sl_pct, etc.)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (symbol_id, tf_minutes, time)
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS ix_super_entry_signals_time
    ON trade.super_entry_signals (time DESC);

CREATE INDEX IF NOT EXISTS ix_super_entry_signals_symbol_time
    ON trade.super_entry_signals (symbol, time DESC);

CREATE INDEX IF NOT EXISTS ix_super_entry_signals_score
    ON trade.super_entry_signals (combined_score DESC, time DESC);

CREATE INDEX IF NOT EXISTS ix_super_entry_signals_tf_time
    ON trade.super_entry_signals (tf_minutes, time DESC);

-- Comment
COMMENT ON TABLE trade.super_entry_signals IS 
    'Signals generated by the Super Entry ML strategy. '
    'Each row represents a high-probability entry point detected by the model.';
