-- 092_pump_dump_signals.sql
-- DDL for Pump/Dump Detection Strategy signals table
-- Generated signals from the ML-based Pump/Dump model (two models: pump + dump)

CREATE TABLE IF NOT EXISTS trade.pump_dump_signals (
    time            TIMESTAMPTZ NOT NULL,
    time_ms         BIGINT NOT NULL,
    symbol          TEXT NOT NULL,
    symbol_id       BIGINT NOT NULL,
    tf_minutes      SMALLINT NOT NULL,           -- finest TF where features were extracted
    side            SMALLINT NOT NULL,            -- 1=LONG(PUMP), -1=SHORT(DUMP)
    event_type      TEXT NOT NULL,                -- 'PUMP' or 'DUMP'
    entry_price     FLOAT8 NOT NULL,
    sl_price        FLOAT8 NOT NULL,
    tp_price        FLOAT8 NOT NULL,
    pred            REAL NOT NULL,                -- model prediction probability [0..1]
    finest_tf       SMALLINT NOT NULL,            -- finest TF reached during feature extraction
    move_pct        FLOAT8 NOT NULL DEFAULT 0.0,  -- estimated/target move percentage
    max_hold_bars   SMALLINT NOT NULL DEFAULT 10, -- max candles to hold before force-close
    strategy        TEXT NOT NULL DEFAULT 'pump_dump_v1',
    reason          JSONB,                        -- full metadata
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (symbol_id, tf_minutes, time)
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS ix_pump_dump_signals_time
    ON trade.pump_dump_signals (time DESC);

CREATE INDEX IF NOT EXISTS ix_pump_dump_signals_symbol_time
    ON trade.pump_dump_signals (symbol, time DESC);

CREATE INDEX IF NOT EXISTS ix_pump_dump_signals_pred
    ON trade.pump_dump_signals (pred DESC, time DESC);

CREATE INDEX IF NOT EXISTS ix_pump_dump_signals_event_type
    ON trade.pump_dump_signals (event_type, time DESC);

CREATE INDEX IF NOT EXISTS ix_pump_dump_signals_tf_time
    ON trade.pump_dump_signals (tf_minutes, time DESC);

-- Comment
COMMENT ON TABLE trade.pump_dump_signals IS 
    'Signals generated by the Pump/Dump ML strategy. '
    'Each row represents a predicted pump or dump event detected by the model. '
    'Min pred threshold: 0.65, target: 15%, max hold: 10 bars.';
