-- 100_ewmac_signals.sql
-- DDL for EWMAC (Exponentially Weighted Moving Average Crossover) Strategy signals
--
-- EWMAC is a trend-following strategy based on Robert Carver's "Systematic Trading".
-- Signal = (EMA_fast - EMA_slow) / volatility (ATR-normalized).
-- Multiple crossover pairs are used: (2,8), (4,16), (8,32), (16,64), (32,128), (64,256).
-- The aggregate signal combines all pairs with equal weighting.

CREATE TABLE IF NOT EXISTS trade.ewmac_signals (
    time            TIMESTAMPTZ NOT NULL,
    time_ms         BIGINT NOT NULL,
    symbol          TEXT NOT NULL,
    symbol_id       BIGINT NOT NULL,
    tf_minutes      SMALLINT NOT NULL,
    side            SMALLINT NOT NULL,           -- 1=LONG, -1=SHORT
    entry_price     FLOAT8 NOT NULL,
    sl_price        FLOAT8 NOT NULL,
    tp_price        FLOAT8 NOT NULL,

    -- EWMAC-specific fields
    raw_signal      FLOAT8 NOT NULL DEFAULT 0.0, -- raw EWMAC value (unnormalized aggregate)
    norm_signal     FLOAT8 NOT NULL DEFAULT 0.0, -- volatility-normalized aggregate signal
    forecast        FLOAT8 NOT NULL DEFAULT 0.0, -- scaled forecast [-20, +20] (Carver convention)
    signal_strength REAL NOT NULL DEFAULT 0.0,   -- |forecast| / 20 (0..1 range for scoring)

    -- Per-pair raw crossover values (for debugging / analysis)
    ewmac_2_8      FLOAT8,   -- EMA(2) - EMA(8) / ATR
    ewmac_4_16     FLOAT8,   -- EMA(4) - EMA(16) / ATR
    ewmac_8_32     FLOAT8,   -- EMA(8) - EMA(32) / ATR
    ewmac_16_64    FLOAT8,   -- EMA(16) - EMA(64) / ATR
    ewmac_32_128   FLOAT8,   -- EMA(32) - EMA(128) / ATR
    ewmac_64_256   FLOAT8,   -- EMA(64) - EMA(256) / ATR

    atr_pct         REAL NOT NULL DEFAULT 0.0,   -- ATR / close * 100
    strategy        TEXT NOT NULL DEFAULT 'ewmac_v1',
    reason          JSONB,                       -- full metadata
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (symbol_id, tf_minutes, time)
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS ix_ewmac_signals_time
    ON trade.ewmac_signals (time DESC);

CREATE INDEX IF NOT EXISTS ix_ewmac_signals_symbol_time
    ON trade.ewmac_signals (symbol, time DESC);

CREATE INDEX IF NOT EXISTS ix_ewmac_signals_forecast
    ON trade.ewmac_signals (forecast DESC, time DESC);

CREATE INDEX IF NOT EXISTS ix_ewmac_signals_tf_time
    ON trade.ewmac_signals (tf_minutes, time DESC);

CREATE INDEX IF NOT EXISTS ix_ewmac_signals_strength
    ON trade.ewmac_signals (signal_strength DESC, time DESC);

-- Comment
COMMENT ON TABLE trade.ewmac_signals IS
    'Signals generated by the EWMAC (Exponentially Weighted Moving Average Crossover) strategy. '
    'Each row represents a trend-following signal with aggregate forecast from multiple EMA pairs. '
    'Based on Robert Carver''s Systematic Trading methodology.';
