binance_testnet = false
database_url = "postgres://postgres:postgres@127.0.0.1:5433/timescaledb_binance"
kafka_brokers = "localhost:19092"
kafka_group_id = "order-manager"
leverage = 10
max_hold_bars = 25
max_orders_at_a_time = 10
max_price_drift_pct = 0.25
order_type = "futures_oco"
scan_interval_secs = 30
signal_score_max_15m = 0.9
signal_score_max_1d = 0.89
signal_score_max_1h = 0.9
signal_score_max_1m = 0.89
signal_score_max_4h = 0.9
signal_score_max_5m = 0.9
signal_score_min_15m = 0.75
signal_score_min_1d = 0.55
signal_score_min_1h = 0.55
signal_score_min_1m = 0.55
signal_score_min_4h = 0.55
signal_score_min_5m = 0.8
strategy_type = "ml_super_entry"
tf_15m_pct = 10
tf_1d_pct = 0
tf_1h_pct = 70
tf_1m_pct = 0
tf_4h_pct = 20
tf_5m_pct = 0
topic_orders_cmd = "orders.cmd"
topic_positions = "positions.updates"
tracker_interval_secs = 2
trade_size_type = "percent_depo"
trade_size_value = 10.0
trading_mode = "auto"
