[package]
name = "market_data"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "market_data"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rmp-serde = "1.1"
futures = "0.3"
axum = "0.7"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

rdkafka = { version = "0.37", features = ["cmake-build"] }
tokio-postgres = "0.7"
chrono = { version = "0.4", features = ["serde"] }

common = { path = "../common" }
connections = { path = "../connections" }
data_writer = { path = "../data_writer" }

tokio-tungstenite = "0.20"
futures-util = "0.3"


