#!/usr/bin/env python3
"""
train_final_scorer.py — Train XGBoost model for Signal Quality Scorer.

Input:  backtest_results.csv (generated by Rust backtester with partial close strategy)
Output: models/signal_quality_v1.ubj (XGBoost model for Rust inference)

Usage:
    python trainer/src/train_final_scorer.py [--csv backtest_results.csv] [--gpu]

Workflow:
    1. Load CSV with signal features + backtest labels (with partial close data)
    2. Feature engineering (derived features)
    3. Train/val split (time-based, not random — avoid look-ahead bias!)
    4. Train XGBoost binary classifier (predict: did signal reach TP1?)
    5. Evaluate (AUC, precision, recall, confusion matrix)
    6. Save model as .ubj (universal binary JSON — Rust-compatible)
    7. Export feature importance for analysis

Backtester partial close strategy:
    - TP1 hit → close 50%, trail SL below TP1
    - TP2 hit → close 30%, trail SL below TP2
    - TP3 hit → close remaining 20%
    - label_pnl_pct is the weighted PnL across all partial closes
"""

import argparse
import os
import sys
import json
import numpy as np
import pandas as pd

try:
    import xgboost as xgb
    from sklearn.metrics import (
        roc_auc_score, precision_score, recall_score,
        classification_report, confusion_matrix
    )
except ImportError:
    print("ERROR: Required packages not installed.")
    print("  pip install xgboost scikit-learn pandas numpy")
    sys.exit(1)


# Feature columns (must match SignalFeatures::feature_names() in Rust)
FEATURE_COLS = [
    "tf_minutes", "side", "final_score", "ml_score", "heur_score",
    "entry_price", "sl_pct", "tp1_pct", "tp2_pct", "tp3_pct",
    "risk_reward", "risk_reward_tp2",
    "predictors_score", "raw_signals_score", "indicators_score", "market_score",
    "coverage_score", "consensus_score",
    "price10_score", "bounce_prob", "bounce_score", "breakout_prob", "breakout_score",
    "trend_strength", "momentum_strength", "volatility_regime", "volume_spike_score",
    "level_aware", "market_quality_score",
]

# Outcome columns from partial close backtester (NOT features — used for analysis only)
TP_HIT_COLS = ["tp1_hit", "tp2_hit", "tp3_hit"]

LABEL_COL = "label_win"  # 1.0 = reached at least TP1 (partial close), 0.0 = hit SL or expired


def load_data(csv_path: str) -> pd.DataFrame:
    """Load and validate backtester CSV (with partial close columns)"""
    print(f"Loading data from {csv_path}...")
    df = pd.read_csv(csv_path)
    print(f"  Loaded {len(df)} rows, {len(df.columns)} columns")
    print(f"  Columns: {list(df.columns)}")

    # Check required columns
    all_required = FEATURE_COLS + TP_HIT_COLS + [LABEL_COL]
    missing = [c for c in all_required if c not in df.columns]
    if missing:
        print(f"  WARNING: Missing columns: {missing}")
        # Fill missing with 0
        for c in missing:
            df[c] = 0.0

    # Basic stats
    n_win = (df[LABEL_COL] == 1.0).sum()
    n_loss = (df[LABEL_COL] == 0.0).sum()
    print(f"  Labels: {n_win} wins ({n_win/len(df)*100:.1f}%), {n_loss} losses ({n_loss/len(df)*100:.1f}%)")

    # Partial close TP level distribution
    if all(c in df.columns for c in TP_HIT_COLS):
        tp1_cnt = (df["tp1_hit"] == 1).sum()
        tp2_cnt = (df["tp2_hit"] == 1).sum()
        tp3_cnt = (df["tp3_hit"] == 1).sum()
        print(f"  TP Levels Hit: TP1={tp1_cnt} ({tp1_cnt/len(df)*100:.1f}%), "
              f"TP2={tp2_cnt} ({tp2_cnt/len(df)*100:.1f}%), "
              f"TP3={tp3_cnt} ({tp3_cnt/len(df)*100:.1f}%)")

    # PnL distribution
    if "label_pnl_pct" in df.columns:
        avg_pnl = df["label_pnl_pct"].mean()
        avg_win_pnl = df.loc[df[LABEL_COL] == 1.0, "label_pnl_pct"].mean() if n_win > 0 else 0
        avg_loss_pnl = df.loc[df[LABEL_COL] == 0.0, "label_pnl_pct"].mean() if n_loss > 0 else 0
        print(f"  PnL (partial close): avg={avg_pnl*100:.4f}%, "
              f"wins={avg_win_pnl*100:.4f}%, losses={avg_loss_pnl*100:.4f}%")

    return df


def add_derived_features(df: pd.DataFrame) -> pd.DataFrame:
    """Add engineered features that improve model quality"""
    # Score ratios
    df["pred_vs_raw"] = df["predictors_score"] / (df["raw_signals_score"] + 1e-8)
    df["pred_vs_ind"] = df["predictors_score"] / (df["indicators_score"] + 1e-8)

    # Agreement strength (low variance = all components agree)
    score_cols = ["predictors_score", "raw_signals_score", "indicators_score", "market_score"]
    df["component_std"] = df[score_cols].std(axis=1)
    df["component_min"] = df[score_cols].min(axis=1)

    # ML-Heur gap
    df["ml_heur_gap"] = abs(df["ml_score"] - df["heur_score"])

    # Risk-adjusted score
    df["score_per_risk"] = df["final_score"] / (df["sl_pct"] + 1e-8)
    
    # Handle quality_grade (string column) - encode as numeric
    if "quality_grade" in df.columns:
        # Map grades to numeric: A=4, B=3, C=2, D=1, ?=0
        grade_map = {'A': 4.0, 'B': 3.0, 'C': 2.0, 'D': 1.0, '?': 0.0}
        df["quality_grade"] = df["quality_grade"].map(grade_map).fillna(0.0)

    return df


def train_model(df: pd.DataFrame, use_gpu: bool = False) -> tuple:
    """Train XGBoost model with time-based split"""

    # Time-based split: first 80% for train, last 20% for validation
    # This prevents look-ahead bias (unlike random split!)
    split_idx = int(len(df) * 0.80)
    train_df = df.iloc[:split_idx]
    val_df = df.iloc[split_idx:]

    print(f"\nTrain/Val split (time-based):")
    print(f"  Train: {len(train_df)} rows")
    print(f"  Val:   {len(val_df)} rows")

    # Feature columns (original + derived)
    all_feature_cols = FEATURE_COLS + [
        "pred_vs_raw", "pred_vs_ind", "component_std", "component_min",
        "ml_heur_gap", "score_per_risk"
    ]

    X_train = train_df[all_feature_cols].values.astype(np.float32)
    y_train = train_df[LABEL_COL].values.astype(np.float32)
    X_val = val_df[all_feature_cols].values.astype(np.float32)
    y_val = val_df[LABEL_COL].values.astype(np.float32)

    # DMatrix
    dtrain = xgb.DMatrix(X_train, label=y_train, feature_names=all_feature_cols)
    dval = xgb.DMatrix(X_val, label=y_val, feature_names=all_feature_cols)

    # Class imbalance handling
    n_pos = y_train.sum()
    n_neg = len(y_train) - n_pos
    scale_pos_weight = n_neg / max(n_pos, 1)

    # XGBoost parameters
    params = {
        "objective": "binary:logistic",
        "eval_metric": ["auc", "logloss"],
        "eta": 0.05,
        "max_depth": 6,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
        "min_child_weight": 5,
        "scale_pos_weight": scale_pos_weight,
        "tree_method": "hist",  # Use 'hist' for both CPU/GPU in XGBoost 3.x
        "device": "cuda" if use_gpu else "cpu",  # New parameter in XGBoost 3.x
        "verbosity": 1,
    }

    print(f"\nTraining XGBoost...")
    print(f"  scale_pos_weight: {scale_pos_weight:.2f}")
    print(f"  tree_method: {params['tree_method']}")

    evals = [(dtrain, "train"), (dval, "val")]
    model = xgb.train(
        params,
        dtrain,
        num_boost_round=500,
        evals=evals,
        early_stopping_rounds=30,
        verbose_eval=50,
    )

    # Evaluate
    y_pred_prob = model.predict(dval)
    y_pred = (y_pred_prob >= 0.5).astype(int)

    auc = roc_auc_score(y_val, y_pred_prob)
    precision = precision_score(y_val, y_pred, zero_division=0)
    recall = recall_score(y_val, y_pred, zero_division=0)

    print(f"\n=== Validation Results ===")
    print(f"  AUC:       {auc:.4f}")
    print(f"  Precision: {precision:.4f}")
    print(f"  Recall:    {recall:.4f}")
    print(f"\nClassification Report:")
    print(classification_report(y_val, y_pred, target_names=["Loss/Expired", "Win"]))
    print(f"Confusion Matrix:")
    print(confusion_matrix(y_val, y_pred))

    # Feature importance
    importance = model.get_score(importance_type="gain")
    sorted_imp = sorted(importance.items(), key=lambda x: x[1], reverse=True)
    print(f"\nTop 15 Features by Gain:")
    for name, gain in sorted_imp[:15]:
        print(f"  {name:30s} {gain:.1f}")

    return model, all_feature_cols, {"auc": auc, "precision": precision, "recall": recall}


def save_model(model, feature_names: list, metrics: dict, output_dir: str):
    """Save model in .ubj format (Rust-compatible) + metadata"""
    os.makedirs(output_dir, exist_ok=True)

    # Save model as UBJ (Universal Binary JSON — XGBoost native, Rust-compatible)
    model_path = os.path.join(output_dir, "signal_quality_v1.ubj")
    model.save_model(model_path)
    print(f"\nModel saved: {model_path}")

    # Also save as JSON for debugging
    json_path = os.path.join(output_dir, "signal_quality_v1.json")
    model.save_model(json_path)
    print(f"Model JSON:  {json_path}")

    # Save metadata
    meta = {
        "model_type": "xgboost_binary_classifier",
        "objective": "binary:logistic",
        "target": "signal reaches TP1 (partial close: 50% at TP1, 30% at TP2, 20% at TP3)",
        "feature_names": feature_names,
        "n_features": len(feature_names),
        "metrics": metrics,
        "best_iteration": model.best_iteration,
        "n_trees": model.best_iteration + 1,
        "note": "Output is win probability [0,1]. Convert to quality_multiplier: 0.5 + prob. "
                "PnL uses partial close strategy with trailing SL.",
        "partial_close_config": {
            "tp1_close_pct": 0.50,
            "tp2_close_pct": 0.30,
            "tp3_close_pct": 0.20,
            "trailing_sl_buffer": 0.001,
        },
    }
    meta_path = os.path.join(output_dir, "signal_quality_v1_meta.json")
    with open(meta_path, "w") as f:
        json.dump(meta, f, indent=2)
    print(f"Metadata:    {meta_path}")


def main():
    parser = argparse.ArgumentParser(description="Train Signal Quality XGBoost Model")
    parser.add_argument("--csv", default="backtest_results.csv", help="Path to backtest CSV")
    parser.add_argument("--output-dir", default="models", help="Output directory for model files")
    parser.add_argument("--gpu", action="store_true", help="Use GPU for training")
    args = parser.parse_args()

    if not os.path.exists(args.csv):
        print(f"ERROR: CSV file not found: {args.csv}")
        print(f"Run the backtester first: ./scripts/backtester.sh")
        sys.exit(1)

    # Load
    df = load_data(args.csv)

    if len(df) < 100:
        print(f"WARNING: Only {len(df)} samples. Need at least 1000+ for meaningful training.")
        if len(df) < 20:
            print("Too few samples to train. Exiting.")
            sys.exit(1)

    # Feature engineering
    df = add_derived_features(df)

    # Train
    model, feature_names, metrics = train_model(df, use_gpu=args.gpu)

    # Save
    save_model(model, feature_names, metrics, args.output_dir)

    print(f"\n✅ Training complete!")
    print(f"   Model: {args.output_dir}/signal_quality_v1.ubj")
    print(f"   Load in Rust: MlQualityScorer::new(\"models/signal_quality_v1.ubj\")")


if __name__ == "__main__":
    main()
