#!/usr/bin/env python3
"""
train_super_entry.py — Train XGBoost models for Super Entry Strategy.

Input:  super_entry_dataset.csv (generated by Rust dataset builder)
Output:
  - models/super_entry_v1_tf{X}.ubj  — P(super) binary classifier
  - models/super_dir_v1_tf{X}.ubj    — P(direction=LONG) binary classifier

Usage:
    python trainer/src/train_super_entry.py [--csv super_entry_dataset.csv] [--gpu] [--output-dir models]

WORKFLOW:
  1. Load CSV with indicator features + labels (is_super, direction, magnitude_pct)
  2. Split by pairs (80/20) to avoid look-ahead bias
  3. For each timeframe:
     a. Train P(super) binary classifier (is_super label)
     b. Train P(direction) binary classifier (direction label: LONG=1, SHORT=0)
  4. Evaluate metrics: AUC, precision, recall per TF
  5. Save models as .ubj (Rust-compatible)
"""

import argparse
import hashlib
import json
import os
import sys

import numpy as np
import pandas as pd

try:
    import xgboost as xgb
    from sklearn.metrics import (
        roc_auc_score, precision_score, recall_score,
        classification_report, confusion_matrix
    )
except ImportError:
    print("ERROR: Required packages not installed.")
    print("  pip install xgboost scikit-learn pandas numpy")
    sys.exit(1)


# Indicator features (must match Rust INDICATOR_FEATURES order)
INDICATOR_FEATURES = [
    "rsi", "cci", "stoch_k", "stoch_d", "williams",
    "macd", "macd_signal", "macd_hist",
    "adx", "sma", "ema_20", "ema_50", "ema_200",
    "bb_upper", "bb_mid", "bb_lower", "atr",
    "obv", "vwap", "volume_spike",
    "trend", "trend_short", "poc",
    # Alligator (3 features)
    "alligator_jaw", "alligator_teeth", "alligator_lips",
    # New indicators v2 (7 features)
    "mfi", "fibo_pivot", "fibo_r1", "fibo_s1",
    "supertrend", "supertrend_dir", "cmf",
]

# Derived features (must match Rust DERIVED_FEATURES order)
DERIVED_FEATURES = [
    "rsi_norm", "cci_norm", "stoch_norm", "williams_norm",
    "bb_position", "bb_width_pct", "atr_pct",
    "price_vs_sma", "price_vs_ema20", "price_vs_ema50",
    "price_vs_ema200", "price_vs_vwap",
    "macd_norm", "obv_change_pct", "volume_spike_flag",
    # New derived v2 (4 features)
    "mfi_norm", "price_vs_fibo_pivot", "price_vs_supertrend",
    "alligator_spread",
]

# Dynamic temporal features (must match Rust DYNAMIC_FEATURES order)
# These capture HOW indicators are changing over time (lookback windows: 3, 5, 10, 15 bars)
# Critical for direction prediction — static snapshots give AUC ~0.50 (random)
DYNAMIC_FEATURES = [
    # Window 3 bars
    "price_return_lb3", "atr_ratio_lb3", "rsi_slope_lb3",
    "trend_persist_lb3", "trend_short_persist_lb3",
    "adx_slope_lb3", "macd_hist_slope_lb3", "ema20_direction_lb3",
    # Window 5 bars
    "price_return_lb5", "atr_ratio_lb5", "rsi_slope_lb5",
    "trend_persist_lb5", "trend_short_persist_lb5",
    "adx_slope_lb5", "macd_hist_slope_lb5", "ema20_direction_lb5",
    # Window 10 bars
    "price_return_lb10", "atr_ratio_lb10", "rsi_slope_lb10",
    "trend_persist_lb10", "trend_short_persist_lb10",
    "adx_slope_lb10", "macd_hist_slope_lb10", "ema20_direction_lb10",
    # Window 15 bars
    "price_return_lb15", "atr_ratio_lb15", "rsi_slope_lb15",
    "trend_persist_lb15", "trend_short_persist_lb15",
    "adx_slope_lb15", "macd_hist_slope_lb15", "ema20_direction_lb15",
    # Aggregate features (6)
    "supertrend_consistency", "trend_alignment",
    "price_accel", "volume_trend_ratio",
    "ema_convergence_change", "high_low_pressure",
]

# Static features (indicators + derived) — 52 total
STATIC_FEATURES = INDICATOR_FEATURES + DERIVED_FEATURES
# All features including dynamic — 90 total
ALL_FEATURES = STATIC_FEATURES + DYNAMIC_FEATURES

# TF target move percentages (must match Rust config::tf_target_move_pct)
TF_TARGET_MOVE_PCT = {
    1: 1.2,
    5: 2.8,
    15: 3.5,
    60: 5.0,
    240: 7.5,
    1440: 10.0,
}

TIMEFRAMES = [1, 5, 15, 60, 240, 1440]


def load_data(csv_path: str) -> pd.DataFrame:
    """Load and validate super entry dataset CSV"""
    print(f"Loading data from {csv_path}...")
    df = pd.read_csv(csv_path)
    print(f"  Loaded {len(df)} rows, {len(df.columns)} columns")

    # Validate required columns
    required = ALL_FEATURES + ["symbol", "tf_minutes", "direction", "magnitude_pct", "is_super"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        print(f"  WARNING: Missing columns: {missing}")
        for c in missing:
            df[c] = 0.0

    # Feature count verification
    n_static = len(STATIC_FEATURES)
    n_dynamic = len(DYNAMIC_FEATURES)
    print(f"  Static features: {n_static}, Dynamic features: {n_dynamic}, Total: {len(ALL_FEATURES)}")

    # Stats
    n_super = (df["is_super"] == 1).sum()
    print(f"  Super examples: {n_super} ({n_super / len(df) * 100:.1f}%)")
    print(f"  By TF:")
    for tf in sorted(df["tf_minutes"].unique()):
        tf_df = df[df["tf_minutes"] == tf]
        tf_super = (tf_df["is_super"] == 1).sum()
        print(f"    {tf}m: {len(tf_df)} total, {tf_super} super ({tf_super / len(tf_df) * 100:.1f}%)")

    return df


def split_by_pairs(df: pd.DataFrame, train_ratio: float = 0.8):
    """Split dataset by pairs (not by time) to avoid look-ahead bias."""
    symbols = df["symbol"].unique()
    np.random.seed(42)
    np.random.shuffle(symbols)

    n_train = int(len(symbols) * train_ratio)
    train_symbols = set(symbols[:n_train])
    test_symbols = set(symbols[n_train:])

    train_df = df[df["symbol"].isin(train_symbols)].copy()
    test_df = df[df["symbol"].isin(test_symbols)].copy()

    print(f"\n  Pair-based split:")
    print(f"    Train: {len(train_symbols)} pairs, {len(train_df)} rows")
    print(f"    Test:  {len(test_symbols)} pairs, {len(test_df)} rows")

    return train_df, test_df


def train_binary(train_df, test_df, label_col, feature_cols, use_gpu=False,
                 model_name="", custom_params=None, num_boost_round=500,
                 early_stopping_rounds=30):
    """Train binary XGBoost and evaluate.
    
    Args:
        custom_params: dict of XGBoost params to override defaults
        num_boost_round: max number of boosting rounds
        early_stopping_rounds: early stop patience
    """
    X_train = train_df[feature_cols].values.astype(np.float32)
    y_train = train_df[label_col].values.astype(np.float32)

    X_test = test_df[feature_cols].values.astype(np.float32)
    y_test = test_df[label_col].values.astype(np.float32)

    # Replace NaN/inf
    X_train = np.nan_to_num(X_train, nan=0.0, posinf=0.0, neginf=0.0)
    X_test = np.nan_to_num(X_test, nan=0.0, posinf=0.0, neginf=0.0)

    dtrain = xgb.DMatrix(X_train, label=y_train, feature_names=feature_cols)
    dtest = xgb.DMatrix(X_test, label=y_test, feature_names=feature_cols)

    # Class imbalance
    n_pos = y_train.sum()
    n_neg = len(y_train) - n_pos
    scale_pos_weight = n_neg / max(n_pos, 1)

    params = {
        "objective": "binary:logistic",
        "eval_metric": ["auc", "logloss"],
        "eta": 0.05,
        "max_depth": 6,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
        "min_child_weight": 5,
        "scale_pos_weight": scale_pos_weight,
        "tree_method": "hist",
        "device": "cuda" if use_gpu else "cpu",
        "verbosity": 1,
    }

    # Apply custom params overrides (e.g., for direction model with different hypers)
    if custom_params:
        params.update(custom_params)

    print(f"\n  Training {model_name}...")
    print(f"    pos/neg: {int(n_pos)}/{int(n_neg)} (scale_pos_weight={scale_pos_weight:.2f})")
    print(f"    params: eta={params['eta']}, max_depth={params['max_depth']}, "
          f"rounds={num_boost_round}, early_stop={early_stopping_rounds}")

    evals = [(dtrain, "train"), (dtest, "test")]
    model = xgb.train(
        params,
        dtrain,
        num_boost_round=num_boost_round,
        evals=evals,
        early_stopping_rounds=early_stopping_rounds,
        verbose_eval=50,
    )

    # Evaluate
    y_pred_prob = model.predict(dtest)
    y_pred = (y_pred_prob >= 0.5).astype(int)

    auc = roc_auc_score(y_test, y_pred_prob) if len(np.unique(y_test)) > 1 else 0.0
    precision = precision_score(y_test, y_pred, zero_division=0)
    recall = recall_score(y_test, y_pred, zero_division=0)

    print(f"\n  === {model_name} Results ===")
    print(f"    AUC:       {auc:.4f}")
    print(f"    Precision: {precision:.4f}")
    print(f"    Recall:    {recall:.4f}")

    if len(np.unique(y_test)) > 1:
        print(f"\n  Classification Report:")
        print(classification_report(y_test, y_pred, target_names=["Negative", "Positive"]))

    # Feature importance
    importance = model.get_score(importance_type="gain")
    sorted_imp = sorted(importance.items(), key=lambda x: x[1], reverse=True)
    print(f"\n  Top 10 Features by Gain:")
    for name, gain in sorted_imp[:10]:
        print(f"    {name:30s} {gain:.1f}")

    metrics = {"auc": auc, "precision": precision, "recall": recall}
    return model, metrics


def save_model(model, feature_names, tf, task_name, metrics, output_dir):
    """Save model as .ubj + schema + metadata."""
    os.makedirs(output_dir, exist_ok=True)

    model_name = f"{task_name}_v1_tf{tf}"

    # UBJ model
    ubj_path = os.path.join(output_dir, f"{model_name}.ubj")
    model.save_model(ubj_path)
    print(f"  Model: {ubj_path}")

    # JSON model (for debugging)
    json_model_path = os.path.join(output_dir, f"{model_name}.json")
    model.save_model(json_model_path)

    # Schema
    schema = {
        "schema_id": hashlib.sha256(",".join(feature_names).encode()).hexdigest() + f"_tf{tf}",
        "features": feature_names,
        "task": task_name,
        "tf_minutes": tf,
        "outputs": 1,
        "objective": "binary:logistic",
    }
    schema_path = os.path.join(output_dir, f"{model_name}.schema.json")
    with open(schema_path, "w") as f:
        json.dump(schema, f, indent=2)
    print(f"  Schema: {schema_path}")

    # Metadata
    meta = {
        "model_type": "xgboost_binary_classifier",
        "objective": "binary:logistic",
        "target": task_name,
        "feature_names": feature_names,
        "n_features": len(feature_names),
        "metrics": metrics,
        "best_iteration": model.best_iteration,
        "n_trees": model.best_iteration + 1,
        "strategy": "ml_entry_strategy",
        "target_move_pct": TF_TARGET_MOVE_PCT.get(tf, 0),
    }
    meta_path = os.path.join(output_dir, f"{model_name}_meta.json")
    with open(meta_path, "w") as f:
        json.dump(meta, f, indent=2)


def main():
    parser = argparse.ArgumentParser(description="Train Super Entry XGBoost Models")
    parser.add_argument("--csv", default="dataset/super_entry_dataset.csv", help="Path to dataset CSV")
    parser.add_argument("--output-dir", default="models", help="Output directory")
    parser.add_argument("--gpu", action="store_true", help="Use GPU training")
    parser.add_argument("--train-split", type=float, default=0.8, help="Train split ratio (by pairs)")
    args = parser.parse_args()

    if not os.path.exists(args.csv):
        print(f"ERROR: {args.csv} not found!")
        print("Generate dataset first:")
        print("  cargo run --release -p ml_entry_strategy --bin super_entry_dataset")
        sys.exit(1)

    # Load
    df = load_data(args.csv)

    if len(df) < 100:
        print(f"Too few samples ({len(df)}). Need 1000+ for meaningful training.")
        sys.exit(1)

    # Train per TF
    for tf in TIMEFRAMES:
        tf_df = df[df["tf_minutes"] == tf].copy()
        if len(tf_df) < 50:
            print(f"\nSkipping TF {tf}m: only {len(tf_df)} samples")
            continue

        print(f"\n{'=' * 60}")
        print(f"Training models for TF {tf}m ({len(tf_df)} samples)")
        print(f"  Target move: {TF_TARGET_MOVE_PCT.get(tf, 0)}%")
        print(f"{'=' * 60}")

        # Split by pairs
        train_df, test_df = split_by_pairs(tf_df, args.train_split)

        if len(train_df) < 30 or len(test_df) < 10:
            print(f"  Not enough data after split. Skipping.")
            continue

        # 1. Train P(super) classifier
        super_model, super_metrics = train_binary(
            train_df, test_df,
            label_col="is_super",
            feature_cols=ALL_FEATURES,
            use_gpu=args.gpu,
            model_name=f"super_entry TF{tf}m"
        )
        save_model(super_model, ALL_FEATURES, tf, "super_entry", super_metrics, args.output_dir)

        # 2. Train P(direction=LONG) classifier
        # Label: 1 = LONG (direction == 1), 0 = SHORT (direction == -1)
        # Uses enhanced hyperparams + ALL_FEATURES (including dynamic temporal features)
        # Dynamic features (price_return, atr_ratio, trend_persist, etc.) are critical
        # for direction — they capture HOW the market is moving, not just static state.
        train_df_dir = train_df.copy()
        test_df_dir = test_df.copy()
        train_df_dir["label_long"] = (train_df_dir["direction"] == 1).astype(int)
        test_df_dir["label_long"] = (test_df_dir["direction"] == 1).astype(int)

        # Direction model gets stronger hyperparameters:
        # - Lower learning rate (0.03) for better generalization
        # - Deeper trees (max_depth=8) to capture temporal feature interactions
        # - More regularization (lambda=3, alpha=0.5) to prevent overfitting
        # - More rounds (1500) with slower learning
        # - Higher colsample (0.9) since dynamic features are all informative
        dir_params = {
            "eta": 0.03,
            "max_depth": 8,
            "subsample": 0.85,
            "colsample_bytree": 0.9,
            "min_child_weight": 10,
            "lambda": 3.0,       # L2 regularization
            "alpha": 0.5,        # L1 regularization
            "gamma": 0.1,        # min split loss
        }

        dir_model, dir_metrics = train_binary(
            train_df_dir, test_df_dir,
            label_col="label_long",
            feature_cols=ALL_FEATURES,
            use_gpu=args.gpu,
            model_name=f"super_dir TF{tf}m",
            custom_params=dir_params,
            num_boost_round=1500,
            early_stopping_rounds=50,
        )
        save_model(dir_model, ALL_FEATURES, tf, "super_dir", dir_metrics, args.output_dir)

    print(f"\n{'=' * 60}")
    print(f"✅ Super Entry training complete!")
    print(f"   Models saved to: {args.output_dir}/")
    print(f"")
    print(f"   Next steps:")
    print(f"   1. Run backtest: cargo run --release -p ml_entry_strategy --bin super_entry_backtest")
    print(f"   2. Or use via script: ./scripts/super_entry.sh --backtest")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    main()
