#!/usr/bin/env python3
"""
train_entry_policy.py — Train XGBoost models for Entry Agent.

Input:  entry_policy_dataset.csv (generated by Rust backtester with entry_policy_labeler)
Output: 
  - models/entry_enter_v1_tf{X}.ubj — Model for ENTER decision
  - models/entry_cancel_v1_tf{X}.ubj — Model for CANCEL decision

Usage:
    python trainer/src/train_entry_policy.py [--csv entry_policy_dataset.csv] [--gpu]

Workflow:
    1. Load CSV with signal features + entry policy labels
    2. Feature engineering (derived features + temporal features)
    3. Train/val split (time-based, not random — avoid look-ahead bias!)
    4. Train XGBoost binary classifiers (ENTER and CANCEL)
    5. Evaluate (AUC, precision, recall, confusion matrix)
    6. Save models as .ubj (universal binary JSON — Rust-compatible)
    7. Export feature importance for analysis

Entry Agent Decision Logic:
    - ENTER: probability(enter) >= threshold AND (prob_enter - prob_cancel) >= margin
    - CANCEL: probability(cancel) >= threshold AND prob_cancel > prob_enter
    - WAIT: otherwise (wait for next bar)

This allows the agent to:
    - Wait for better entry conditions instead of entering immediately
    - Cancel setups that are no longer valid
    - Enter only when probability/reward is maximal
"""

import argparse
import os
import sys
import json
import hashlib
import numpy as np
import pandas as pd

try:
    import xgboost as xgb
    from sklearn.model_selection import TimeSeriesSplit
    from sklearn.metrics import (
        roc_auc_score, precision_score, recall_score,
        classification_report, confusion_matrix
    )
except ImportError:
    print("ERROR: Required packages not installed.")
    print("  pip install xgboost scikit-learn pandas numpy")
    sys.exit(1)


# Feature columns (must match Rust feature extraction)
FEATURE_COLS = [
    "tf_minutes", "side", "final_score", "ml_score", "heur_score",
    "entry_price", "sl_pct", "tp1_pct", "tp2_pct", "tp3_pct",
    "risk_reward", "risk_reward_tp2",
    "predictors_score", "raw_signals_score", "indicators_score", "market_score",
    "coverage_score", "consensus_score",
    "price10_score", "bounce_prob", "bounce_score", "breakout_prob", "breakout_score",
    "trend_strength", "momentum_strength", "volatility_regime", "volume_spike_score",
    "level_aware", "market_quality_score",
    "quality_multiplier", "quality_grade", "original_score",
    "pred_vs_raw", "pred_vs_ind", "component_std", "component_min", "ml_heur_gap", "score_per_risk",
    "atr_pct", "market_factor", "score_factor",
    # Phase 1: Impulse + Momentum features (for early entry detection)
    "impulse_phase", "momentum_acceleration", "rsi_slope", "volume_impulse_confirm",
    # Phase 2: SR distance features
    "nearest_support_dist_atr", "nearest_resistance_dist_atr", "sr_position",
    # Phase 3: EMA/BB features
    "ema_stack", "price_vs_emas", "bb_position", "bb_width",
    # Temporal features (added by labeler)
    "elapsed", "remaining",
]

LABEL_ENTER = "label_enter"
LABEL_CANCEL = "label_cancel"
WEIGHT_COL = "weight"


def load_data(csv_path: str) -> pd.DataFrame:
    """Load and validate entry policy CSV"""
    print(f"Loading data from {csv_path}...")
    df = pd.read_csv(csv_path)
    print(f"  Loaded {len(df)} rows, {len(df.columns)} columns")
    
    # Check required columns
    required = FEATURE_COLS + [LABEL_ENTER, LABEL_CANCEL, WEIGHT_COL]
    missing = [c for c in required if c not in df.columns]
    if missing:
        print(f"  WARNING: Missing columns: {missing}")
        for c in missing:
            df[c] = 0.0
    
    # Basic stats
    n_enter = (df[LABEL_ENTER] == 1.0).sum()
    n_cancel = (df[LABEL_CANCEL] == 1.0).sum()
    n_wait = len(df) - n_enter - n_cancel
    print(f"  Labels: {n_enter} ENTER ({n_enter/len(df)*100:.1f}%), "
          f"{n_cancel} CANCEL ({n_cancel/len(df)*100:.1f}%), "
          f"{n_wait} WAIT ({n_wait/len(df)*100:.1f}%)")
    
    # Distribution by timeframe
    if "tf_minutes" in df.columns:
        print(f"  By TF:")
        for tf in sorted(df["tf_minutes"].unique()):
            cnt = (df["tf_minutes"] == tf).sum()
            print(f"    {tf}m: {cnt} ({cnt/len(df)*100:.1f}%)")
    
    return df


def add_derived_features(df: pd.DataFrame) -> pd.DataFrame:
    """Add engineered features that improve model quality"""
    # Score ratios (already in CSV but ensure consistency)
    df["pred_vs_raw"] = df["predictors_score"] / (df["raw_signals_score"] + 1e-8)
    df["pred_vs_ind"] = df["predictors_score"] / (df["indicators_score"] + 1e-8)
    
    # Agreement strength (low variance = all components agree)
    score_cols = ["predictors_score", "raw_signals_score", "indicators_score", "market_score"]
    df["component_std"] = df[score_cols].std(axis=1)
    df["component_min"] = df[score_cols].min(axis=1)
    
    # ML-Heur gap
    df["ml_heur_gap"] = abs(df["ml_score"] - df["heur_score"])
    
    # Risk-adjusted score
    df["score_per_risk"] = df["final_score"] / (df["sl_pct"] + 1e-8)
    
    # Temporal features (already in CSV but ensure)
    # elapsed = bars since setup started
    # remaining = bars left in entry window
    
    # Interaction features
    df["score_x_elapsed"] = df["final_score"] * df["elapsed"]
    df["score_x_remaining"] = df["final_score"] * df["remaining"]
    df["urgency"] = df["remaining"] / (df["elapsed"] + 1)  # High urgency = little time left
    
    # Handle quality_grade (string column) - encode as numeric or drop
    # For now, replace with 0 (will be removed from features anyway)
    if "quality_grade" in df.columns:
        # Map grades to numeric: A=4, B=3, C=2, D=1, ?=0
        grade_map = {'A': 4.0, 'B': 3.0, 'C': 2.0, 'D': 1.0, '?': 0.0}
        df["quality_grade"] = df["quality_grade"].map(grade_map).fillna(0.0)
    
    return df


def train_binary(df: pd.DataFrame, label_col: str, use_gpu: bool = False) -> tuple:
    """Train binary XGBoost model with time-based split"""
    
    # Time-based split: first 80% for train, last 20% for validation
    split_idx = int(len(df) * 0.80)
    train_df = df.iloc[:split_idx]
    val_df = df.iloc[split_idx:]
    
    print(f"\nTrain/Val split (time-based):")
    print(f"  Train: {len(train_df)} rows")
    print(f"  Val:   {len(val_df)} rows")
    
    # Feature columns (original + derived)
    all_feature_cols = FEATURE_COLS + [
        "score_x_elapsed", "score_x_remaining", "urgency"
    ]
    
    X_train = train_df[all_feature_cols].values.astype(np.float32)
    y_train = train_df[label_col].values.astype(np.float32)
    w_train = train_df[WEIGHT_COL].values.astype(np.float32) if WEIGHT_COL in train_df.columns else None
    
    X_val = val_df[all_feature_cols].values.astype(np.float32)
    y_val = val_df[label_col].values.astype(np.float32)
    w_val = val_df[WEIGHT_COL].values.astype(np.float32) if WEIGHT_COL in val_df.columns else None
    
    # DMatrix
    dtrain = xgb.DMatrix(X_train, label=y_train, feature_names=all_feature_cols, weight=w_train)
    dval = xgb.DMatrix(X_val, label=y_val, feature_names=all_feature_cols, weight=w_val)
    
    # Class imbalance handling
    n_pos = y_train.sum()
    n_neg = len(y_train) - n_pos
    scale_pos_weight = n_neg / max(n_pos, 1)
    
    # XGBoost parameters
    params = {
        "objective": "binary:logistic",
        "eval_metric": ["auc", "logloss"],
        "eta": 0.05,
        "max_depth": 6,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
        "min_child_weight": 5,
        "scale_pos_weight": scale_pos_weight,
        "tree_method": "hist",  # Use 'hist' for both CPU/GPU in XGBoost 3.x
        "device": "cuda" if use_gpu else "cpu",  # New parameter in XGBoost 3.x
        "verbosity": 1,
    }
    
    print(f"\nTraining XGBoost for {label_col}...")
    print(f"  scale_pos_weight: {scale_pos_weight:.2f}")
    print(f"  tree_method: {params['tree_method']}")
    
    evals = [(dtrain, "train"), (dval, "val")]
    model = xgb.train(
        params,
        dtrain,
        num_boost_round=500,
        evals=evals,
        early_stopping_rounds=30,
        verbose_eval=50,
    )
    
    # Evaluate
    y_pred_prob = model.predict(dval)
    y_pred = (y_pred_prob >= 0.5).astype(int)
    
    auc = roc_auc_score(y_val, y_pred_prob)
    precision = precision_score(y_val, y_pred, zero_division=0)
    recall = recall_score(y_val, y_pred, zero_division=0)
    
    print(f"\n=== Validation Results for {label_col} ===")
    print(f"  AUC:       {auc:.4f}")
    print(f"  Precision: {precision:.4f}")
    print(f"  Recall:    {recall:.4f}")
    print(f"\nClassification Report:")
    print(classification_report(y_val, y_pred, target_names=["Negative", "Positive"]))
    print(f"Confusion Matrix:")
    print(confusion_matrix(y_val, y_pred))
    
    # Feature importance
    importance = model.get_score(importance_type="gain")
    sorted_imp = sorted(importance.items(), key=lambda x: x[1], reverse=True)
    print(f"\nTop 15 Features by Gain:")
    for name, gain in sorted_imp[:15]:
        print(f"  {name:30s} {gain:.1f}")
    
    return model, all_feature_cols, {"auc": auc, "precision": precision, "recall": recall}


def save_model(model, feature_names: list, tf: int, task_name: str, task: str, metrics: dict, output_dir: str):
    """Save model in .ubj format (Rust-compatible) + metadata"""
    os.makedirs(output_dir, exist_ok=True)

    # Model name
    model_name = f"{task_name}_v1_tf{tf}"
    
    # Save model as UBJ (Universal Binary JSON — XGBoost native, Rust-compatible)
    model_path = os.path.join(output_dir, f"{model_name}.ubj")
    model.save_model(model_path)
    print(f"\nModel saved: {model_path}")
    
    # Also save as JSON for debugging
    json_path = os.path.join(output_dir, f"{model_name}.json")
    model.save_model(json_path)
    print(f"Model JSON:  {json_path}")
    
    # Schema for Rust inference (feature ordering)
    schema = {
        "schema_id": hashlib.sha256(",".join(feature_names).encode()).hexdigest() + f"_tf{tf}",
        "features": feature_names,
        "task": task_name,
        "tf_minutes": tf,
        "outputs": 1,
        "objective": "binary:logistic",
    }
    schema_path = os.path.join(output_dir, f"{model_name}.schema.json")
    with open(schema_path, "w") as f:
        json.dump(schema, f, indent=2)
    print(f"Schema:      {schema_path}")
    
    # Metadata
    meta = {
        "model_type": "xgboost_binary_classifier",
        "objective": "binary:logistic",
        "target": task,
        "feature_names": feature_names,
        "n_features": len(feature_names),
        "metrics": metrics,
        "best_iteration": model.best_iteration,
        "n_trees": model.best_iteration + 1,
        "note": "Entry Agent decision model. Output is probability [0,1]. "
                "Use with companion model for ENTER/CANCEL/WAIT decision.",
        "decision_logic": {
            "ENTER": "prob_enter >= 0.5 AND (prob_enter - prob_cancel) >= 0.1",
            "CANCEL": "prob_cancel >= 0.5 AND prob_cancel > prob_enter",
            "WAIT": "otherwise"
        }
    }
    meta_path = os.path.join(output_dir, f"{model_name}_meta.json")
    with open(meta_path, "w") as f:
        json.dump(meta, f, indent=2)
    print(f"Metadata:    {meta_path}")


def main():
    parser = argparse.ArgumentParser(description="Train Entry Policy XGBoost Models")
    parser.add_argument("--csv", default="entry_policy_dataset.csv", help="Path to entry policy CSV")
    parser.add_argument("--output-dir", default="models", help="Output directory for model files")
    parser.add_argument("--gpu", action="store_true", help="Use GPU for training")
    args = parser.parse_args()
    
    if not os.path.exists(args.csv):
        print(f"ERROR: CSV file not found: {args.csv}")
        print(f"Run the backtester first: ./scripts/backtester.sh")
        sys.exit(1)
    
    # Load
    df = load_data(args.csv)
    
    if len(df) < 100:
        print(f"WARNING: Only {len(df)} samples. Need at least 1000+ for meaningful training.")
        if len(df) < 20:
            print("Too few samples to train. Exiting.")
            sys.exit(1)
    
    # Feature engineering
    df = add_derived_features(df)
    
    # Train per timeframe
    timeframes = [1, 5, 15, 60, 240]
    
    for tf in timeframes:
        tf_df = df[df["tf_minutes"] == tf].copy()
        if len(tf_df) < 50:
            print(f"\nSkipping TF {tf}m: only {len(tf_df)} samples")
            continue
        
        print(f"\n{'='*60}")
        print(f"Training for TF {tf}m ({len(tf_df)} samples)")
        print(f"{'='*60}")
        
        # Train ENTER model
        enter_model, enter_feats, enter_metrics = train_binary(
            tf_df.copy(), LABEL_ENTER, use_gpu=args.gpu
        )
        save_model(
            enter_model, enter_feats, tf,
            "entry_enter", "entry_policy_enter_now", enter_metrics, args.output_dir
        )
        
        # Train CANCEL model
        cancel_model, cancel_feats, cancel_metrics = train_binary(
            tf_df.copy(), LABEL_CANCEL, use_gpu=args.gpu
        )
        save_model(
            cancel_model, cancel_feats, tf,
            "entry_cancel", "entry_policy_cancel_setup", cancel_metrics, args.output_dir
        )
    
    print(f"\n{'='*60}")
    print(f"✅ Training complete!")
    print(f"   Models saved to: {args.output_dir}/")
    print(f"   Load in Rust: ModelManager with kind='entry_enter' / 'entry_cancel'")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
